title: EECS 203 Notes
author: Brian Oo
description: A quick-reference little side project. Transcribing a majority of the EECS 203 cirriculum at the University of Michigan as notes.
theme: minima
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

