title: EECS 203 Notes
author:
  name: Brian Oo
  email: brianoo@umich.edu
description: A quick-reference little side project. Transcribing a majority of the EECS 203 cirriculum at the University of Michigan as notes.
theme: minima
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

