theme: jekyll-theme-minimal
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
